# Generated by Django 4.2 on 2026-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('shipped', 'Отгружен'), ('done', 'Завершен'), ('canceled', 'Отменен')], db_index=True, default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
