# Generated by Django 4.2 on 2026-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sitesetting_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=0, help_text='0 = без ограничения', verbose_name='Макс. кол-во в заказе'),
        ),
    ]
