# Generated by Django 4.2 on 2026-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_max_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения'),
        ),
    ]
