# Generated by Django 4.2 on 2026-04-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_blogpost_cover_brand_logo_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Снимается при отписке.', verbose_name='Активна')),
                ('source', models.CharField(blank=True, default='footer', help_text='Где оставили email: footer, checkout, manual...', max_length=64, verbose_name='Источник')),
                ('unsubscribe_token', models.CharField(editable=False, help_text='Секретный токен для ссылки отписки.', max_length=64, unique=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отписался')),
            ],
            options={
                'verbose_name': 'Подписчик рассылки',
                'verbose_name_plural': 'Подписчики рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('preview', models.CharField(blank=True, help_text='Короткая строка, которую показывают почтовые клиенты рядом с темой.', max_length=200, verbose_name='Превью-строка')),
                ('heading', models.CharField(max_length=200, verbose_name='Заголовок в письме')),
                ('intro_html', models.TextField(blank=True, help_text='Основной текст перед карточками товаров. Разрешён базовый HTML.', verbose_name='Вступление (HTML)')),
                ('cta_label', models.CharField(default='Перейти в каталог', max_length=60, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(default='/catalog/', help_text='Абсолютная ссылка или относительная (будет преобразована).', max_length=300, verbose_name='Ссылка кнопки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлено')], default='draft', max_length=16, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Доставлено писем')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='До 6 товаров, которые покажутся в письме карточками.', related_name='campaigns', to='shop.product')),
            ],
            options={
                'verbose_name': 'Рассылка (кампания)',
                'verbose_name_plural': 'Рассылки (кампании)',
                'ordering': ['-created_at'],
            },
        ),
    ]
