# Generated by Django 4.2 on 2026-04-21 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_newslettersubscriber_newslettercampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(db_index=True, help_text='Заглавные латиница/цифры. Например: PAPERLY10, SUMMER20.', max_length=32, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание (для админа)')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент от суммы'), ('fixed', 'Фиксированная сумма'), ('free_shipping', 'Бесплатная доставка')], default='percent', max_length=16, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Для процента — 1..100. Для фикс. суммы — рубли. Для free_shipping можно 0.', max_digits=10, verbose_name='Размер')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Необязательный потолок для процентных скидок. Оставьте пустым — без ограничения.', max_digits=10, null=True, verbose_name='Максимум скидки, ₽')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Заказ ниже этой суммы не принимает промокод.', max_digits=10, verbose_name='Мин. сумма заказа, ₽')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = без ограничения. После достижения лимита код отключается.', verbose_name='Лимит использований всего')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, help_text='Сколько раз один email может использовать код. 0 = без ограничения.', verbose_name='Лимит на пользователя')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Использовано раз')),
                ('audience', models.CharField(choices=[('all', 'Все покупатели'), ('new_only', 'Только для новых клиентов'), ('registered', 'Только для зарегистрированных')], default='all', max_length=16, verbose_name='Для кого')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Код действует только на товары из выбранных категорий.', related_name='promo_codes', to='shop.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Код действует только на выбранные товары. Пусто — весь каталог.', related_name='promo_codes', to='shop.product')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('amount_discounted', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма скидки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='shop.order', verbose_name='Заказ')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='shop.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Использование промокода',
                'verbose_name_plural': 'Использования промокодов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.promocode', verbose_name='Промокод'),
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['promo', 'user'], name='shop_promoc_promo_i_4a5b84_idx'),
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['promo', 'email'], name='shop_promoc_promo_i_f7bca9_idx'),
        ),
    ]
