# Generated by Django 4.2 on 2026-04-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_promocode_promocoderedemption_order_promo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('label', models.CharField(help_text='Видно в aria-label. Например: «Telegram», «ВКонтакте».', max_length=60, verbose_name='Название')),
                ('url', models.URLField(max_length=300, verbose_name='Ссылка')),
                ('icon_class', models.CharField(blank=True, help_text='Класс иконки из Bootstrap Icons, например: bi-telegram, bi-youtube. Используется, если не загружена картинка.', max_length=60, verbose_name='Bootstrap-иконка')),
                ('icon_image', models.ImageField(blank=True, help_text='PNG/SVG ≈ 48×48. Если загружено — используется вместо bi-класса.', null=True, upload_to='social-icons/', verbose_name='Иконка (картинка)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать в футере')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
