# Generated by Django 4.2 on 2026-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Показывать на странице /promotions/. Включайте только для «широких» кампаний (сезонные распродажи, баннерные акции). Точечные коды (для рассылок, cart-abandonment, VIP) оставляйте выключенными — они раздаются адресно.', verbose_name='Публиковать на сайте'),
        ),
    ]
