# Generated by Django 4.2 on 2026-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_create_manager_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='page_type',
            field=models.CharField(choices=[('index', 'Главная'), ('about', 'О магазине'), ('delivery', 'Доставка и оплата'), ('guarantee', 'Гарантия и возврат'), ('wholesale', 'Оптовым клиентам'), ('pickup', 'Пункты самовывоза'), ('privacy', 'Политика конфиденциальности'), ('terms', 'Пользовательское соглашение'), ('offer', 'Договор оферты'), ('cookies', 'Политика cookie')], max_length=24, verbose_name='Тип страницы'),
        ),
    ]
