# Generated by Django 4.2 on 2026-04-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_seed_legal_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='shop_catego_parent__114883_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='shop_order_email_fa7dab_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='shop_order_status_700268_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='shop_promot_is_acti_732373_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile', 'address_type'), name='uniq_default_address_per_profile_type'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock__gte', 0)), name='product_stock_non_negative'),
        ),
    ]
