# Generated by Django 4.2 on 2026-04-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_audit_constraints_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='2–3 предложения для сниппета в поисковой выдаче (≤160 симв. идеально).', max_length=300, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='То, что видно во вкладке браузера и в выдаче поисковиков. Если пусто — берётся обычный заголовок страницы.', max_length=200, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Превью при репосте ссылки в Telegram/VK/Facebook. Рекомендуем 1200×630.', upload_to='seo/', verbose_name='Картинка для соцсетей (OG image)'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Если файл не загружен, можно указать прямую ссылку.', verbose_name='URL картинки для соцсетей'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cookies_banner_text',
            field=models.TextField(blank=True, help_text='Если пусто — используется стандартный текст.', verbose_name='Текст cookie-баннера'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если задано — на сайте показывается плашка «Бесплатная доставка от X ₽».', max_digits=10, null=True, verbose_name='Бесплатная доставка от суммы, ₽'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_text',
            field=models.CharField(blank=True, help_text='Если оставить пустым, текст соберётся автоматически.', max_length=200, verbose_name='Текст плашки бесплатной доставки'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Координата для карты на странице «Контакты».', max_digits=9, null=True, verbose_name='Широта офиса'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота офиса'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sales_email',
            field=models.EmailField(blank=True, help_text='Если оставить пустым — везде показывается основной email.', max_length=254, verbose_name='Email отдела продаж'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='Например, для оптовых клиентов или другого региона.', max_length=32, verbose_name='Телефон (дополнительный)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='wholesale_email',
            field=models.EmailField(blank=True, help_text='Используется на странице «Оптовым клиентам». Пусто — основной email.', max_length=254, verbose_name='Email для оптовых клиентов'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='work_hours',
            field=models.CharField(blank=True, help_text='Например: «Пн–Пт 09:00–21:00, Сб–Вс 10:00–18:00».', max_length=255, verbose_name='Часы работы (полные)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='work_hours_short',
            field=models.CharField(blank=True, help_text='Для шапки/футера: «09:00–21:00 ежедневно».', max_length=120, verbose_name='Часы работы (короткая запись)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (основной)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон (основной)'),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hero_eyebrow', models.CharField(blank=True, help_text='Маленькая строка над h1. Пример: «Paperly — канцтовары».', max_length=120, verbose_name='Hero · подпись над заголовком')),
                ('hero_title', models.CharField(blank=True, help_text='Главный заголовок страницы. Пример: «Соберите идеальный набор».', max_length=255, verbose_name='Hero · основной заголовок')),
                ('hero_title_accent', models.CharField(blank=True, help_text='Часть заголовка, которая выделится цветом. Пример: «учёбы, офиса и творчества».', max_length=200, verbose_name='Hero · акцентный фрагмент')),
                ('hero_subtitle', models.TextField(blank=True, help_text='2–3 предложения под заголовком. Можно писать обычным текстом.', verbose_name='Hero · подзаголовок (lead)')),
                ('hero_cta_primary_label', models.CharField(blank=True, max_length=60, verbose_name='Hero · CTA #1 · текст')),
                ('hero_cta_primary_url', models.CharField(blank=True, help_text='Абсолютная или относительная ссылка. Пример: «/catalog/», «https://…».', max_length=300, verbose_name='Hero · CTA #1 · ссылка')),
                ('hero_cta_primary_icon', models.CharField(blank=True, help_text='Bootstrap-icons класс, например: bi-grid, bi-arrow-right.', max_length=60, verbose_name='Hero · CTA #1 · иконка')),
                ('hero_cta_secondary_label', models.CharField(blank=True, max_length=60, verbose_name='Hero · CTA #2 · текст')),
                ('hero_cta_secondary_url', models.CharField(blank=True, max_length=300, verbose_name='Hero · CTA #2 · ссылка')),
                ('hero_cta_secondary_icon', models.CharField(blank=True, max_length=60, verbose_name='Hero · CTA #2 · иконка')),
                ('show_stats', models.BooleanField(default=True, help_text='Плашка с автоматическими цифрами (товары/бренды/пункты).', verbose_name='Показывать блок «цифры о магазине»')),
                ('show_categories', models.BooleanField(default=True, verbose_name='Показывать «Популярные категории»')),
                ('show_promotions', models.BooleanField(default=True, verbose_name='Показывать «Акции и скидки»')),
                ('show_new_arrivals', models.BooleanField(default=True, verbose_name='Показывать «Новинки»')),
                ('show_bestsellers', models.BooleanField(default=True, verbose_name='Показывать «Хиты продаж»')),
                ('show_brands', models.BooleanField(default=True, verbose_name='Показывать «Популярные бренды»')),
                ('show_services', models.BooleanField(default=True, verbose_name='Показывать карточки сервисов (доставка/пункты/опт)')),
                ('show_features', models.BooleanField(default=True, verbose_name='Показывать блок «Почему покупают»')),
                ('features_title', models.CharField(blank=True, help_text='Если пусто — «Почему покупают в {название_сайта}».', max_length=200, verbose_name='Заголовок блока «Почему мы»')),
                ('features_eyebrow', models.CharField(blank=True, help_text='По умолчанию — «Почему мы».', max_length=120, verbose_name='Подпись над «Почему мы»')),
                ('featured_categories', models.ManyToManyField(blank=True, help_text='Если выбраны — заменяют дефолтные карточки в блоке «Популярные категории». Иконка/цвет берётся из «Карточек категорий на главной» (см. ниже) при совпадении.', related_name='featured_on_homepage', to='shop.category', verbose_name='Витринные категории')),
                ('featured_products', models.ManyToManyField(blank=True, help_text='Если задано — рендерятся под hero как «Рекомендуем». До 8 шт по sort_order.', related_name='featured_on_homepage', to='shop.product', verbose_name='Витринные товары (опц.)')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='HomeHeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('badge', models.CharField(blank=True, help_text='Маленькая плашка над заголовком, например «Снова в школу».', max_length=60, verbose_name='Бейдж (необязательно)')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок карточки')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap-icons класс, например: bi-backpack, bi-briefcase, bi-palette.', max_length=60, verbose_name='Иконка')),
                ('url', models.CharField(help_text='Куда ведёт карточка. Пример: «/catalog/?category=kids».', max_length=300, verbose_name='Ссылка')),
                ('color_variant', models.CharField(choices=[('school', 'Школа (бирюза)'), ('office', 'Офис (нейтральный)'), ('art', 'Творчество (амбер)'), ('default', 'Базовый')], default='default', max_length=16, verbose_name='Цветовая схема')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_cards', to='shop.homepage', verbose_name='Главная')),
            ],
            options={
                'verbose_name': 'Hero · карточка',
                'verbose_name_plural': 'Hero · карточки',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('icon_class', models.CharField(help_text='Bootstrap-icons. Примеры: bi-box-seam, bi-lightning-charge, bi-arrow-counterclockwise, bi-percent.', max_length=60, verbose_name='Иконка')),
                ('color_variant', models.CharField(choices=[('teal', 'Бирюзовый'), ('amber', 'Янтарный'), ('rose', 'Розовый'), ('indigo', 'Индиго')], default='teal', max_length=16, verbose_name='Цвет иконки')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.homepage', verbose_name='Главная')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подпись (мелкая)')),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap-icons класс. Примеры: bi-journal-bookmark, bi-pencil, bi-palette.', max_length=60, verbose_name='Иконка')),
                ('url', models.CharField(help_text='Например: «/catalog/?category=paper» или «/brands/».', max_length=300, verbose_name='Ссылка')),
                ('color_modifier', models.CharField(blank=True, help_text='Хвост к классу .category-card—. Допустимые: paper, writing, art, office, kids, brands. Пусто — без подсветки.', max_length=24, verbose_name='CSS-модификатор')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_cards', to='shop.homepage', verbose_name='Главная')),
            ],
            options={
                'verbose_name': 'Карточка категории',
                'verbose_name_plural': 'Карточки категорий',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
